In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr = np.array(lista)

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# Index
arr[0]

1

In [14]:
matriz[0][1]

2

In [15]:
matriz[0]

array([1, 2, 3])

In [16]:
matriz[0, 2]

3

In [17]:
arr[0 : 3]

array([1, 2, 3])

In [18]:
arr[1 : 6]

array([2, 3, 4, 5, 6])

In [19]:
arr[::3]

array([1, 4, 7])

In [20]:
arr[-1]

9

In [22]:
arr[-3:]

array([7, 8, 9])

In [23]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])