In [1]:
import numpy as np 

In [4]:
arr = np.random.randint(1, 20, 10)

In [5]:
matriz = arr.reshape(2, 5)

In [6]:
matriz

array([[ 1,  8, 14, 12,  5],
       [17,  1, 15,  7,  9]])

In [7]:
arr

array([ 1,  8, 14, 12,  5, 17,  1, 15,  7,  9])

In [9]:
arr.max()

17

In [12]:
matriz.max(1)

array([14, 17])

In [13]:
matriz.max(0)

array([17,  8, 15, 12,  9])

In [15]:
matriz.argmax(1)

array([2, 0], dtype=int64)

In [16]:
matriz.argmax(0)

array([1, 0, 1, 0, 1], dtype=int64)

In [17]:
arr.ptp()

16

In [18]:
arr.min()

1

In [19]:
matriz.ptp()

16

In [23]:
np.percentile(arr, 100)

17.0

In [25]:
arr.sort()
arr

array([ 1,  1,  5,  7,  8,  9, 12, 14, 15, 17])

In [27]:
arr.mean()

8.9

In [29]:
np.median(arr)

8.5

In [32]:
np.std(arr)**2

28.290000000000003

In [31]:
np.var(arr)

28.290000000000003

In [35]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [36]:
b = np.array([5, 6])

In [37]:
c = np.concatenate((a, np.expand_dims(b, axis=0)), axis=0)

In [38]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
D = np.concatenate((a, np.expand_dims(b, axis=0).T), axis=1)
D

array([[1, 2, 5],
       [3, 4, 6]])