In [1]:
import numpy as np

In [2]:
lista = [1, 2]
lista

[1, 2]

In [4]:
lista * 2

[1, 2, 1, 2]

In [8]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr2 = arr.copy()
arr2 = arr2 *2
arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
1/(arr + arr2)

C:\Users\Daniel\AppData\Local\Temp\ipykernel_10900\1140990425.py:1: RuntimeWarning: divide by zero encountered in divide
  1/(arr + arr2)


array([       inf, 0.33333333, 0.16666667, 0.11111111, 0.08333333,
       0.06666667, 0.05555556, 0.04761905, 0.04166667, 0.03703704,
       0.03333333])