In [1]:
import numpy as np

In [3]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand()

0.17059187983882507

In [15]:
np.random.rand(4)

array([0.35397663, 0.45418446, 0.57336497, 0.47099053])

In [16]:
np.random.rand(4, 4)

array([[0.85519597, 0.19291555, 0.05507466, 0.54444514],
       [0.98935404, 0.9843014 , 0.28198317, 0.77010456],
       [0.62679437, 0.62320255, 0.37844869, 0.08833086],
       [0.32899534, 0.48223925, 0.27833306, 0.27961635]])

In [17]:
np.random.randint(1, 15)

7

In [18]:
np.random.randint(1, 100, (10, 10))

array([[66, 23, 14,  9, 94, 41, 57, 97, 58, 14],
       [63, 79, 77, 45, 22, 45, 21, 47, 96, 29],
       [47,  6, 42, 70,  1, 65, 18, 50, 34, 42],
       [86,  2, 17, 95, 83, 80, 77, 58,  8, 42],
       [35,  8, 64, 80, 87, 26, 38, 68,  9, 91],
       [65, 80, 53, 58, 48, 42, 98, 10, 13, 78],
       [64, 57, 96, 13, 10, 17, 29, 87, 56,  2],
       [24, 24, 50, 75, 71,  6, 41, 17, 98, 23],
       [89, 36, 28,  2, 35, 70, 23, 69, 82, 84],
       [19, 87, 20, 13, 78, 78, 19, 47, 80,  6]])