In [1]:
import numpy as np

In [2]:
# Matriz 2D

In [3]:
# Tensor 3D

In [4]:
# Tensor - 4d

In [9]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [11]:
Vector = np.array([1,2])
print(Vector)
Vector.ndim

[1 2]


1

In [13]:
matriz = np.array([[1,2], [1,2]])
print(matriz)
matriz.ndim

[[1 2]
 [1 2]]


2

In [16]:
matriz3d = np.array([[[1,2], [1,2], [1,2]], [[1,2], [1,2], [1,2]]])
print(matriz3d)
matriz3d.ndim

[[[1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]]]


3

In [19]:
#agregar dim
expand = np.expand_dims(Vector, axis=0)
print(expand)

[[1 2]]


In [23]:
#Remover dims
print(expand, expand.ndim) 
vector_2 = np.squeeze(expand)
print(vector_2, vector_2.ndim)

[[1 2]] 2
[1 2] 1
