In [1]:
import numpy as np

In [10]:
arr = np.arange(0, 11)

In [11]:
arr_copy = arr.copy()

In [13]:
trozo_de_arr = arr_copy[0:6]

In [14]:
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
trozo_de_arr[:] = 0

In [16]:
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])