In [1]:
import numpy as np

In [5]:
arr =np.random.randint(1, 10, (3, 2))
arr

array([[2, 2],
       [9, 5],
       [7, 5]])

In [6]:
arr.shape

(3, 2)

In [7]:
arr.reshape(1, 6)

array([[2, 2, 9, 5, 7, 5]])

In [8]:
arr.reshape(2, 3)

array([[2, 2, 9],
       [5, 7, 5]])