In [1]:
import numpy as np

In [4]:
arr =np.array([1, 2, 3, 4])
arr.dtype

dtype('int32')

In [5]:
arr =np.array([1, 2, 3, 4], dtype="float64")
arr.dtype

dtype('float64')

In [6]:
arr

array([1., 2., 3., 4.])

In [7]:
arr.astype(np.float64)

array([1., 2., 3., 4.])

In [9]:
arr =np.array([0, 1, 2, 3, 4])
arr.astype(np.bool_)

array([False,  True,  True,  True,  True])

In [11]:
arr =np.array([0, 1, 2, 3, 4])
arr.astype(np.string_)

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

In [12]:
arr =np.array(['0', '1', '2', '3', '4'])
arr.astype(np.int8)

array([0, 1, 2, 3, 4], dtype=int8)